import Head from 'next/head'
import { useState } from 'react'
import Addnote from '../components/Addnote'
import DisplayNotes from '../components/DisplayNotes'
import EditNote from '../components/EditNote'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [visible, setvisible] = useState(0)


  return (
    <div className={styles.container}>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Addnote />
      < EditNote visible={visible} setvisible={setvisible} />
      <DisplayNotes setvisible={setvisible} />

    </div>
  )
}
